
DEFAULT_ITEM_CODE = "000.000.000"
DEFAULT_SUPPLIER_GROUP = "Lieferant"
WAREHOUSE = 'Wielandstr. 32 - SoMiKo'
STANDARD_PRICE_LIST = 'Standard-Vertrieb'
STANDARD_ITEM_GROUP = 'Produkte'
STANDARD_NAMING_SERIES_PINV = 'EK .YYYY.-'
VAT_DESCRIPTION = 'Umsatzsteuer'
DELIVERY_COST_ACCOUNT = '4998 - Vertriebskosten - SoMiKo'
DELIVERY_COST_DESCRIPTION = 'Vertriebskosten'
VALIDITY_DATE = '2020-10-01'

